[Wed Jun 26 17:31:53 2024] 
hello!
[Wed Jun 26 17:31:54 2024] 
hello!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/uoj/judger/judge_client", line 66, in socket_server_loop
    s.bind(('', jconf['socket_port']))
OSError: [Errno 98] Address already in use

[Wed Jun 26 17:31:56 2024] 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 433, in <module>
    main()
  File "/opt/uoj/judger/judge_client", line 403, in main
    start_judger_server()
  File "/opt/uoj/judger/judge_client", line 102, in start_judger_server
    judger_loop()
  File "/opt/uoj/judger/judge_client", line 366, in judger_loop
    raise Exception('socket server exited unexpectedly')
Exception: socket server exited unexpectedly
[Wed Jun 26 18:34:44 2024] {'id': 1, 'problem_id': 1, 'content': {'file_name': '/submission/4151/l93eNr1E7XTPeKM2RZgo', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 18:36:34 2024] {'id': 2, 'problem_id': 1, 'content': {'file_name': '/submission/4726/xssGs4nY5qtnEp9wAHXu', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 18:36:37 2024] {'id': 3, 'problem_id': 1, 'content': {'file_name': '/submission/3045/Wqb2i0IPYca41LreqsYj', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 18:36:43 2024] {'id': 4, 'problem_id': 1, 'content': {'file_name': '/submission/9851/y814eMNNlWML8BGBwX6o', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 18:37:15 2024] {'id': 5, 'problem_id': 1, 'content': {'file_name': '/submission/1336/R3zcQcYH67ELoemzbpDE', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 18:46:50 2024] {'id': 6, 'problem_id': 1, 'content': {'file_name': '/submission/3735/QbIT8Tntp2X6ZzBJJWgV', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:12:52 2024] {'id': 7, 'problem_id': 1, 'content': {'file_name': '/submission/149/Y7Kluw50tfLSw54pBKlq', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:18:16 2024] {'id': 8, 'problem_id': 1, 'content': {'file_name': '/submission/9910/lCTPkyZNBafToQJfRdya', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:18:26 2024] {'id': 9, 'problem_id': 1, 'content': {'file_name': '/submission/1221/NKpqisIaDNSP9nbyFOYg', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:18:50 2024] {'id': 10, 'problem_id': 1, 'content': {'file_name': '/submission/9519/0YB4EcewsjcsWu7o3X0X', 'config': [['ans233wer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:19:31 2024] {'id': 11, 'problem_id': 1, 'content': {'file_name': '/submission/4910/Ke5uxQ3DU6RK1GGZgIR6', 'config': [['ans233wer_language', 'C++'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:52:45 2024] {'id': 12, 'problem_id': 1, 'content': {'file_name': '/submission/2329/5v2hJC5ZcvM8khcEM3gF', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:53:09 2024] {'id': 13, 'problem_id': 1, 'content': {'file_name': '/submission/2681/ddKQMIOKUSTBPy5Zi29W', 'config': [['ans233wer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719397246} 
judging
[Wed Jun 26 19:59:17 2024] {'id': 14, 'problem_id': 1, 'content': {'file_name': '/submission/7131/sOKnsWs6ybM7xk5tivHr', 'config': [['problem_id', '1']]}, 'problem_mtime': 1719402919} 
judging
[Wed Jun 26 20:07:07 2024] {'id': 15, 'problem_id': 2, 'content': {'file_name': '/submission/247/TAwhUm93URXf2eiFSfjj', 'config': [['answer_language', 'C'], ['problem_id', '2']]}, 'problem_mtime': 1719403615} 
judging
[Wed Jun 26 20:07:21 2024] {'id': 16, 'problem_id': 2, 'content': {'file_name': '/submission/7485/SJmQNyTE8vsE1fHxstq9', 'config': [['answer_language', 'C'], ['problem_id', '2']]}, 'problem_mtime': 1719403615} 
judging
[Wed Jun 26 22:15:26 2024] {'id': 17, 'problem_id': 2, 'content': {'file_name': '/submission/2259/idtdhU7xDclrQy03kVv5', 'config': [['answer_language', 'Python3'], ['problem_id', '2']]}, 'problem_mtime': 1719403615} 
judging
[Thu Jun 27 09:13:11 2024] {'id': 18, 'problem_id': 2, 'content': {'file_name': '/submission/274/su87oSCQoIS6g3Mk4QfE', 'config': [['answer_language', 'C++'], ['problem_id', '2']]}, 'problem_mtime': 1719403615} 
judging
[Thu Jun 27 09:51:28 2024] {'id': 19, 'problem_id': 2, 'content': {'file_name': '/submission/8049/ugF7gIHpuGooETIKwbQu', 'config': [['answer_language', 'C++11'], ['problem_id', '2']]}, 'problem_mtime': 1719453050} 
judging
[Thu Jun 27 09:51:54 2024] {'id': 20, 'problem_id': 2, 'content': {'file_name': '/submission/3359/0lL6zMoJogQHs5zakFgW', 'config': [['answer_language', 'C++11'], ['problem_id', '2']]}, 'problem_mtime': 1719453050} 
judging
[Thu Jun 27 10:04:04 2024] 
hello!
[Thu Jun 27 10:16:32 2024] 
hello!
[Thu Jun 27 11:30:20 2024] {'id': 21, 'problem_id': 2, 'content': {'file_name': '/submission/2979/Qhdjd6IW6flvygIq92oI', 'config': [['answer_language', 'C++11'], ['problem_id', '2']]}, 'problem_mtime': 1719453050} 
judging
[Thu Jun 27 11:30:37 2024] {'id': 22, 'problem_id': 2, 'content': {'file_name': '/submission/886/xnuARyjc4AI6NsWBEZV8', 'config': [['answer_language', 'C++'], ['problem_id', '2']]}, 'problem_mtime': 1719453050} 
judging
[Thu Jun 27 11:54:58 2024] {'id': 23, 'problem_id': 1, 'content': {'file_name': '/submission/3437/5dzXWJPMytgmjzvjq7dL', 'config': [['answer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 12:26:41 2024] {'id': 24, 'problem_id': 16, 'content': {'file_name': '/submission/5550/15MCmrvhhjt5v48ltClt', 'config': [['answer_language', 'Python3'], ['problem_id', '16']]}, 'problem_mtime': 1719462120} 
judging
[Thu Jun 27 12:27:40 2024] {'id': 25, 'problem_id': 2, 'content': {'file_name': '/submission/5340/7YjiO5gWTNzWUZa1DbCJ', 'config': [['answer_language', 'Python3'], ['problem_id', '2']]}, 'problem_mtime': 1719460912} 
judging
[Thu Jun 27 12:29:23 2024] {'id': 26, 'problem_id': 2, 'content': {'file_name': '/submission/1215/WNXMEOBJYnUub3sKchPe', 'config': [['answer_language', 'Python3'], ['problem_id', '2']]}, 'problem_mtime': 1719462555} 
judging
[Thu Jun 27 12:29:59 2024] {'id': 27, 'problem_id': 2, 'content': {'file_name': '/submission/1370/o7KM1m3LsIzsgjyysZUj', 'config': [['answer_language', 'Python3'], ['problem_id', '2']]}, 'problem_mtime': 1719462555} 
judging
[Thu Jun 27 12:32:42 2024] {'id': 28, 'problem_id': 9, 'content': {'file_name': '/submission/2167/H12DUiBgf6eA2vrDkffi', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462739} 
judging
[Thu Jun 27 12:32:43 2024] {'id': 28, 'problem_id': 9, 'content': {'file_name': '/submission/2167/H12DUiBgf6eA2vrDkffi', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462739} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 228: invalid continuation byte
[Thu Jun 27 12:33:41 2024] {'id': 29, 'problem_id': 9, 'content': {'file_name': '/submission/5928/OtHU5R3TQ6gPVOqAdkaT', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462739} 
judging
[Thu Jun 27 12:33:42 2024] {'id': 29, 'problem_id': 9, 'content': {'file_name': '/submission/5928/OtHU5R3TQ6gPVOqAdkaT', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462739} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 228-229: invalid continuation byte
[Thu Jun 27 12:35:24 2024] {'id': 30, 'problem_id': 9, 'content': {'file_name': '/submission/8707/o3WIjSYLPRy8l9rtCEPj', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462917} 
judging
[Thu Jun 27 12:35:25 2024] {'id': 30, 'problem_id': 9, 'content': {'file_name': '/submission/8707/o3WIjSYLPRy8l9rtCEPj', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719462917} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 227-228: invalid continuation byte
[Thu Jun 27 12:35:45 2024] {'id': 1, 'problem_id': 9, 'content': {'file_name': '/tmp/3p9BzFdABlSXULkWNj3K', 'config': [['answer_language', 'Python3'], ['problem_id', '9'], ['custom_test', 'on']]}, 'is_custom_test': '', 'problem_mtime': 1719462917} 
judging
[Thu Jun 27 12:36:47 2024] {'id': 31, 'problem_id': 9, 'content': {'file_name': '/submission/2758/sIQoZ1CcQavK6Hk9n3CR', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:36:48 2024] {'id': 31, 'problem_id': 9, 'content': {'file_name': '/submission/2758/sIQoZ1CcQavK6Hk9n3CR', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 227-228: invalid continuation byte
[Thu Jun 27 12:38:48 2024] {'id': 32, 'problem_id': 11, 'content': {'file_name': '/submission/9525/u4djaiNekzjLfuezO29W', 'config': [['answer_language', 'Python3'], ['problem_id', '11']]}, 'problem_mtime': 1719461865} 
judging
[Thu Jun 27 12:40:23 2024] {'id': 33, 'problem_id': 12, 'content': {'file_name': '/submission/4420/PWh1TgtDBN6qFX749AY3', 'config': [['answer_language', 'Python3'], ['problem_id', '12']]}, 'problem_mtime': 1719463205} 
judging
[Thu Jun 27 12:42:34 2024] {'id': 34, 'problem_id': 9, 'content': {'file_name': '/submission/7634/4Yde0MSFWK50dGOvjFEW', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:42:39 2024] {'id': 34, 'problem_id': 9, 'content': {'file_name': '/submission/7634/4Yde0MSFWK50dGOvjFEW', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 232-233: invalid continuation byte
[Thu Jun 27 12:44:50 2024] {'id': 35, 'problem_id': 9, 'content': {'file_name': '/submission/8647/dYXjtkgB9TT55nlHeBQm', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:44:53 2024] {'id': 35, 'problem_id': 9, 'content': {'file_name': '/submission/8647/dYXjtkgB9TT55nlHeBQm', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 231-232: invalid continuation byte
[Thu Jun 27 12:45:26 2024] {'id': 36, 'problem_id': 9, 'content': {'file_name': '/submission/9424/XJA0j4wflLCNSJNt8tAJ', 'config': [['answer_language', 'Java8'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:45:31 2024] {'id': 36, 'problem_id': 9, 'content': {'file_name': '/submission/9424/XJA0j4wflLCNSJNt8tAJ', 'config': [['answer_language', 'Java8'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 231-232: invalid continuation byte
[Thu Jun 27 12:47:28 2024] {'id': 2, 'problem_id': 9, 'content': {'file_name': '/tmp/lRK5pJ1UDDj8TLTvJynJ', 'config': [['answer_language', 'C++'], ['problem_id', '9'], ['custom_test', 'on']]}, 'is_custom_test': '', 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:47:42 2024] {'id': 37, 'problem_id': 9, 'content': {'file_name': '/submission/3301/ZorOnmwFjl0vWi1SU2EW', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:47:58 2024] {'id': 38, 'problem_id': 9, 'content': {'file_name': '/submission/9893/z8phhn6eMWTMmEMrDk9C', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:48:25 2024] {'id': 39, 'problem_id': 9, 'content': {'file_name': '/submission/9627/wXsAO2RwvoRbSTEM0XjK', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:49:14 2024] {'id': 40, 'problem_id': 9, 'content': {'file_name': '/submission/3090/9xvBv9UbDqhq0PGI4zJA', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:49:16 2024] {'id': 40, 'problem_id': 9, 'content': {'file_name': '/submission/3090/9xvBv9UbDqhq0PGI4zJA', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 226-227: invalid continuation byte
[Thu Jun 27 12:49:54 2024] {'id': 41, 'problem_id': 9, 'content': {'file_name': '/submission/9419/X9OGMKG10edKjKeB7Xva', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:50:29 2024] {'id': 42, 'problem_id': 9, 'content': {'file_name': '/submission/1744/M7hE8tDJdGYulkPt2Zs4', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:51:06 2024] {'id': 43, 'problem_id': 9, 'content': {'file_name': '/submission/3115/RBvBVdzkPkrZDzSz2QuT', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:51:07 2024] {'id': 43, 'problem_id': 9, 'content': {'file_name': '/submission/3115/RBvBVdzkPkrZDzSz2QuT', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 226-227: invalid continuation byte
[Thu Jun 27 12:51:29 2024] {'id': 44, 'problem_id': 9, 'content': {'file_name': '/submission/4493/HnRFjulizQGjhtt0Tn9F', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:51:30 2024] {'id': 44, 'problem_id': 9, 'content': {'file_name': '/submission/4493/HnRFjulizQGjhtt0Tn9F', 'config': [['answer_language', 'C++'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 226-227: invalid continuation byte
[Thu Jun 27 12:51:58 2024] {'id': 45, 'problem_id': 9, 'content': {'file_name': '/submission/3637/uiklMHfdldHEgP99lWDD', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:52:18 2024] {'id': 46, 'problem_id': 9, 'content': {'file_name': '/submission/641/BDJuObqqwe3FemZBmfpn', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:52:22 2024] {'id': 46, 'problem_id': 9, 'content': {'file_name': '/submission/641/BDJuObqqwe3FemZBmfpn', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 233-234: invalid continuation byte
[Thu Jun 27 12:52:38 2024] {'id': 47, 'problem_id': 9, 'content': {'file_name': '/submission/6670/2DJVzPmJBb50qA5Yo0uS', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:52:42 2024] {'id': 47, 'problem_id': 9, 'content': {'file_name': '/submission/6670/2DJVzPmJBb50qA5Yo0uS', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 234-235: invalid continuation byte
[Thu Jun 27 12:52:54 2024] {'id': 48, 'problem_id': 9, 'content': {'file_name': '/submission/8783/jvtafbDr2BOfrsdmSxzU', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:53:18 2024] {'id': 49, 'problem_id': 9, 'content': {'file_name': '/submission/6077/k03eZLqm9UokeV29USLo', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:53:42 2024] {'id': 50, 'problem_id': 9, 'content': {'file_name': '/submission/7191/rdBev5hOkq6elkHbKUMW', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719463001} 
judging
[Thu Jun 27 12:54:30 2024] {'id': 51, 'problem_id': 9, 'content': {'file_name': '/submission/4476/BSnvAa2mUP9EflvaiLaq', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464060} 
judging
[Thu Jun 27 12:55:16 2024] {'id': 52, 'problem_id': 9, 'content': {'file_name': '/submission/2557/pn2uIRDMgHGhwaHQpPGS', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464060} 
judging
[Thu Jun 27 12:55:48 2024] {'id': 53, 'problem_id': 9, 'content': {'file_name': '/submission/495/Uz1oR8uad1ykCGRjX0lX', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464060} 
judging
[Thu Jun 27 12:56:11 2024] {'id': 54, 'problem_id': 9, 'content': {'file_name': '/submission/5023/vbzcH1nfw3XNbf821m0P', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464060} 
judging
[Thu Jun 27 12:57:02 2024] {'id': 55, 'problem_id': 9, 'content': {'file_name': '/submission/6271/TMbsQWc0jovOlbuNYNZr', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464207} 
judging
[Thu Jun 27 12:57:19 2024] {'id': 56, 'problem_id': 9, 'content': {'file_name': '/submission/9467/fNTDkZk6jyEplWbsg2Sw', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464207} 
judging
[Thu Jun 27 12:57:23 2024] {'id': 56, 'problem_id': 9, 'content': {'file_name': '/submission/9467/fNTDkZk6jyEplWbsg2Sw', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464207} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 231-232: invalid continuation byte
[Thu Jun 27 13:22:45 2024] {'id': 57, 'problem_id': 9, 'content': {'file_name': '/submission/6424/zVtvi0ZSbU9IBRnfIuYt', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464207} 
judging
[Thu Jun 27 13:23:01 2024] {'id': 58, 'problem_id': 9, 'content': {'file_name': '/submission/3844/IcR9cDOEtSyD20a2A9Ol', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719464207} 
judging
[Thu Jun 27 13:23:45 2024] {'id': 59, 'problem_id': 9, 'content': {'file_name': '/submission/7223/0nQAlvpy8vkvHhjExhWz', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719465817} 
judging
[Thu Jun 27 13:24:09 2024] {'id': 60, 'problem_id': 9, 'content': {'file_name': '/submission/1881/LBstPcAojs62htEHFtnR', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719465817} 
judging
[Thu Jun 27 13:24:13 2024] {'id': 60, 'problem_id': 9, 'content': {'file_name': '/submission/1881/LBstPcAojs62htEHFtnR', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719465817} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 233-234: invalid continuation byte
[Thu Jun 27 13:25:55 2024] {'id': 61, 'problem_id': 10, 'content': {'file_name': '/submission/2884/ChSiuBe9RZcTfyA4XJHt', 'config': [['answer_language', 'Java11'], ['problem_id', '10']]}, 'problem_mtime': 1719461760} 
judging
[Thu Jun 27 13:27:19 2024] {'id': 62, 'problem_id': 10, 'content': {'file_name': '/submission/2904/NnZ685cnkOGZ6k5LxAFw', 'config': [['answer_language', 'Java11'], ['problem_id', '10']]}, 'problem_mtime': 1719466032} 
judging
[Thu Jun 27 13:29:29 2024] {'id': 63, 'problem_id': 9, 'content': {'file_name': '/submission/231/Jh89mTb4kDTFkaRkNz92', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
judging
[Thu Jun 27 13:29:33 2024] {'id': 63, 'problem_id': 9, 'content': {'file_name': '/submission/231/Jh89mTb4kDTFkaRkNz92', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 234-235: invalid continuation byte
[Thu Jun 27 13:29:43 2024] {'id': 63, 'problem_id': 9, 'content': {'file_name': '/submission/231/Jh89mTb4kDTFkaRkNz92', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
judging
[Thu Jun 27 13:29:46 2024] {'id': 63, 'problem_id': 9, 'content': {'file_name': '/submission/231/Jh89mTb4kDTFkaRkNz92', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 234-235: invalid continuation byte
[Thu Jun 27 13:30:09 2024] {'id': 3, 'problem_id': 9, 'content': {'file_name': '/tmp/k2WzIqn4UGfq00u0Wf6Z', 'config': [['answer_language', 'Python3'], ['problem_id', '9'], ['custom_test', 'on']]}, 'is_custom_test': '', 'problem_mtime': 1719466112} 
judging
[Thu Jun 27 13:34:02 2024] {'id': 64, 'problem_id': 9, 'content': {'file_name': '/submission/2884/mFtlk641pfEZZhvMGAmd', 'config': [['answer_language', 'Python3'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
judging
[Thu Jun 27 13:34:16 2024] {'id': 65, 'problem_id': 9, 'content': {'file_name': '/submission/786/I8SP3vLlrYDDQrlZXZ5G', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
judging
[Thu Jun 27 13:34:20 2024] {'id': 65, 'problem_id': 9, 'content': {'file_name': '/submission/786/I8SP3vLlrYDDQrlZXZ5G', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
Traceback (most recent call last):
  File "/opt/uoj/judger/judge_client", line 379, in judger_loop
    res = judge()
  File "/opt/uoj/judger/judge_client", line 262, in judge
    return get_judger_result()
  File "/opt/uoj/judger/judge_client", line 177, in get_judger_result
    line = fres.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 234-235: invalid continuation byte
[Thu Jun 27 13:41:24 2024] {'id': 66, 'problem_id': 1, 'content': {'file_name': '/submission/2539/z4GLJ4l9x2crfFlbZ3DF', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 13:51:52 2024] {'id': 67, 'problem_id': 1, 'content': {'file_name': '/submission/1468/ZlS2iICKjSgnk8oAswGE', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 13:52:19 2024] {'id': 68, 'problem_id': 1, 'content': {'file_name': '/submission/9084/FkZAiz9zDkDhiHdBumLp', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 13:53:03 2024] {'id': 69, 'problem_id': 1, 'content': {'file_name': '/submission/3224/2KGnfBOYnADzxd4UK3rQ', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 17:07:08 2024] {'id': 70, 'problem_id': 1, 'content': {'file_name': '/submission/3678/r5d46STWrPAjJvTJlL9X', 'config': [['answer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 17:09:49 2024] {'id': 71, 'problem_id': 1, 'content': {'file_name': '/submission/3346/5iYSmiYHpzscjIeqq5KN', 'config': [['answer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 17:11:14 2024] {'id': 72, 'problem_id': 1, 'content': {'file_name': '/submission/3583/90nGCEQZ1vWgDpt5SPFy', 'config': [['answer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 17:13:04 2024] {'id': 73, 'problem_id': 1, 'content': {'file_name': '/submission/305/59vjPjikQSzVPAPVxtBx', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Thu Jun 27 17:17:30 2024] {'id': 74, 'problem_id': 1, 'content': {'file_name': '/submission/9571/PEuE9t2Wi35mlSMthVBU', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Fri Jun 28 09:52:31 2024] {'id': 75, 'problem_id': 14, 'content': {'file_name': '/submission/5277/TDUaIEW1s4gwCGDzIOPI', 'config': [['answer_language', 'Python3'], ['problem_id', '14']]}, 'problem_mtime': 1719462022} 
judging
[Fri Jun 28 09:56:18 2024] {'id': 76, 'problem_id': 1, 'content': {'file_name': '/submission/5139/QoCWCjXNq2XXDBUq1DO9', 'config': [['answer_language', 'C'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
[Fri Jun 28 09:57:27 2024] {'id': 77, 'problem_id': 2, 'content': {'file_name': '/submission/9623/hRS5Z9fajv8QNjjNPhwT', 'config': [['answer_language', 'C'], ['problem_id', '2']]}, 'problem_mtime': 1719462555} 
judging
[Fri Jun 28 09:57:57 2024] {'id': 78, 'problem_id': 14, 'content': {'file_name': '/submission/6648/ZZZO5gfn2ymvRv1WRKCC', 'config': [['answer_language', 'Python2'], ['problem_id', '14']]}, 'problem_mtime': 1719462022} 
judging
[Fri Jun 28 09:59:02 2024] {'id': 79, 'problem_id': 14, 'content': {'file_name': '/submission/5477/onUC5zH7GMJtShNF7P0r', 'config': [['answer_language', 'Python2'], ['problem_id', '14']]}, 'problem_mtime': 1719462022} 
judging
[Fri Jun 28 10:00:39 2024] {'id': 80, 'problem_id': 3, 'content': {'file_name': '/submission/2956/8tl9sV0sZhgCD069a1fp', 'config': [['answer_language', 'C'], ['problem_id', '3']]}, 'problem_mtime': 1719462671} 
judging
[Fri Jun 28 10:01:17 2024] {'id': 81, 'problem_id': 4, 'content': {'file_name': '/submission/4958/cNfW1MXhNQvJE1npdART', 'config': [['answer_language', 'C'], ['problem_id', '4']]}, 'problem_mtime': 1719461189} 
judging
[Fri Jun 28 10:02:08 2024] {'id': 82, 'problem_id': 5, 'content': {'file_name': '/submission/5123/kwJdOmCtvKV0QFieMYJ1', 'config': [['answer_language', 'C++11'], ['problem_id', '5']]}, 'problem_mtime': 1719461259} 
judging
[Fri Jun 28 10:02:43 2024] {'id': 83, 'problem_id': 6, 'content': {'file_name': '/submission/1515/T61OnJLuMtoMOfcrKuFA', 'config': [['answer_language', 'C++11'], ['problem_id', '6']]}, 'problem_mtime': 1719461314} 
judging
[Fri Jun 28 10:03:21 2024] {'id': 84, 'problem_id': 7, 'content': {'file_name': '/submission/3748/9aPj2LBac7qaHoLnguvO', 'config': [['answer_language', 'C++11'], ['problem_id', '7']]}, 'problem_mtime': 1719461404} 
judging
[Fri Jun 28 10:03:48 2024] {'id': 85, 'problem_id': 8, 'content': {'file_name': '/submission/4198/zTfVEhEqiMNYmD2xRAwy', 'config': [['answer_language', 'C++11'], ['problem_id', '8']]}, 'problem_mtime': 1719461458} 
judging
[Fri Jun 28 10:06:59 2024] {'id': 86, 'problem_id': 9, 'content': {'file_name': '/submission/920/1GUAwip9BZ0ehxfiNfyd', 'config': [['answer_language', 'Java11'], ['problem_id', '9']]}, 'problem_mtime': 1719466112} 
judging
[Fri Jun 28 10:07:34 2024] {'id': 87, 'problem_id': 10, 'content': {'file_name': '/submission/3716/oLRSDGi5TxSU4qP6gWhM', 'config': [['answer_language', 'Java11'], ['problem_id', '10']]}, 'problem_mtime': 1719466032} 
judging
[Fri Jun 28 10:08:17 2024] {'id': 88, 'problem_id': 11, 'content': {'file_name': '/submission/1413/CHbCUhZGW3HFMldWTKpB', 'config': [['answer_language', 'Java11'], ['problem_id', '11']]}, 'problem_mtime': 1719461865} 
judging
[Fri Jun 28 10:08:23 2024] {'id': 89, 'problem_id': 11, 'content': {'file_name': '/submission/3325/Shssqmff8AWTcopA2WD6', 'config': [['answer_language', 'Java11'], ['problem_id', '11']]}, 'problem_mtime': 1719461865} 
judging
[Fri Jun 28 10:08:58 2024] {'id': 90, 'problem_id': 12, 'content': {'file_name': '/submission/1942/CTgstruJfvs5hESYINEG', 'config': [['answer_language', 'Java11'], ['problem_id', '12']]}, 'problem_mtime': 1719463205} 
judging
[Fri Jun 28 10:09:57 2024] {'id': 91, 'problem_id': 13, 'content': {'file_name': '/submission/1844/OG7KjqvBRv50MAA6PNQE', 'config': [['answer_language', 'Python3'], ['problem_id', '13']]}, 'problem_mtime': 1719461970} 
judging
[Fri Jun 28 10:10:32 2024] {'id': 92, 'problem_id': 14, 'content': {'file_name': '/submission/4732/NAHtD0nAroV1OONsAIsz', 'config': [['answer_language', 'Python3'], ['problem_id', '14']]}, 'problem_mtime': 1719462022} 
judging
[Fri Jun 28 10:11:14 2024] {'id': 93, 'problem_id': 15, 'content': {'file_name': '/submission/796/yiGfktPNo9eAresO7oUN', 'config': [['answer_language', 'Python3'], ['problem_id', '15']]}, 'problem_mtime': 1719462068} 
judging
[Fri Jun 28 10:11:35 2024] {'id': 94, 'problem_id': 16, 'content': {'file_name': '/submission/6074/KUlxEMNAc58llnaJhqQm', 'config': [['answer_language', 'Python3'], ['problem_id', '16']]}, 'problem_mtime': 1719462120} 
judging
[Fri Jun 28 11:15:13 2024] {'id': 95, 'problem_id': 1, 'content': {'file_name': '/submission/3376/3NHWrq6tEARILhSf5cO1', 'config': [['answer_language', 'Python3'], ['problem_id', '1']]}, 'problem_mtime': 1719460412} 
judging
